apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cqlmezleg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cqlmezleg-go 
  name: cqlmezleg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cqlmezleg-go 
